### ISSUE TITLE
ads130e08: build error on esp32s3 target

### ISSUE THREAD

**Issue by jmpmscorp** [UncleRus/esp-idf-lib#513]
### The issue

Default example for ads130e08 component produces some errors when you select esp32s3 as target.

### Which SDK are you using?

esp-idf

### Which version of SDK are you using?

5.x

### Which build target have you used?

- [ ] esp32
- [ ] esp32s2
- [X] esp32s3
- [ ] esp32c2
- [ ] esp8266
- [ ] other

### Component causing the issue

ads130e08

### Anything in the logs that might be useful for us?

```console
Log:



-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- The ASM compiler identification is GNU
-- Found assembler: D:/.espressif5/tools/xtensa-esp32s3-elf/esp-2022r1-11.2.0/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-gcc.exe
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: D:/.espressif5/tools/xtensa-esp32s3-elf/esp-2022r1-11.2.0/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: D:/.espressif5/tools/xtensa-esp32s3-elf/esp-2022r1-11.2.0/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building ESP-IDF components for target esp32s3
-- Project sdkconfig file F:/Tools/espressif/libs/esp-idf-lib-jmpmscorp/examples/ads130e08/default/sdkconfig
Traceback (most recent call last):
  File "F:/Tools/espressif/sdk/v5_0_1/esp-idf/tools/kconfig_new/confgen.py", line 607, in <module>
    main()
  File "F:/Tools/espressif/sdk/v5_0_1/esp-idf/tools/kconfig_new/confgen.py", line 328, in main
    output_function(deprecated_options, config, temp_file)
  File "F:/Tools/espressif/sdk/v5_0_1/esp-idf/tools/kconfig_new/confgen.py", line 440, in write_json
    config_dict = get_json_values(config)
  File "F:/Tools/espressif/sdk/v5_0_1/esp-idf/tools/kconfig_new/confgen.py", line 435, in get_json_values
    write_node(n)
  File "F:/Tools/espressif/sdk/v5_0_1/esp-idf/tools/kconfig_new/confgen.py", line 432, in write_node
    val = int(val)
ValueError: invalid literal for int() with base 10: ''
CMake Error at F:/Tools/espressif/sdk/v5_0_1/esp-idf/tools/cmake/kconfig.cmake:176 (message):
  Failed to run confgen.py
  (d:/.espressif5/python_env/idf5.0_py3.8_env/Scripts/python.exe;F:/Tools/espressif/sdk/v5_0_1/esp-idf/tools/kconfig_new/confgen.py;--list-separator=semicolon;--kconfig;F:/Tools/espressif/sdk/v5_0_1/esp-idf/Kconfig;--sdkconfig-rename;F:/Tools/espressif/sdk/v5_0_1/esp-idf/sdkconfig.rename;--config;F:/Tools/espressif/libs/esp-idf-lib-jmpmscorp/examples/ads130e08/default/sdkconfig;--env-file;F:/Tools/espressif/libs/esp-idf-lib-jmpmscorp/examples/ads130e08/default/build/config.env).
  Error 1
Call Stack (most recent call first):
  F:/Tools/espressif/sdk/v5_0_1/esp-idf/tools/cmake/build.cmake:590 (__kconfig_generate_config)
  F:/Tools/espressif/sdk/v5_0_1/esp-idf/tools/cmake/project.cmake:440 (idf_build_process)
  CMakeLists.txt:8 (project)


-- Configuring incomplete, errors occurred!
See also "F:/Tools/espressif/libs/esp-idf-lib-jmpmscorp/examples/ads130e08/default/build/CMakeFiles/CMakeOutput.log".
```
```


### Additional information or context

I found that error is related with Kconfig file on example. When target is esp32s3, there isn't default pins for SPI host used, so kconfig parser can't set int value.

Also, in main.c file, HOST is set to HSPI_HOST but esp32s3 has not defined this macro. Instead, you should use SPI2_HOST or SPI3_HOST.

### Confirmation

- [X] This report is not a question nor a request for drivers.

**Comment by trombik** [comment]
Fixed in #514
